export const SHIRT_COLORS: Record<
    number,
    {
        hex: string
        ringerHex?: string
        name: string
        colorFamily: string
        displayHueOrder: number
    }
> = {
    1971: {
        hex: '#FAFAFA',
        ringerHex: '#C93A3A',
        name: 'White (Red Ringer)',
        colorFamily: 'White',
        displayHueOrder: 1100,
    },
    1972: {
        hex: '#FAFAFA',
        ringerHex: '#C93A3A',
        name: 'White (Red Ringer)',
        colorFamily: 'White',
        displayHueOrder: 1100,
    },
    1973: {
        hex: '#FAFAFA',
        ringerHex: '#C93A3A',
        name: 'White (Red Ringer)',
        colorFamily: 'White',
        displayHueOrder: 1100,
    },
    1974: {
        hex: '#FAFAFA',
        ringerHex: '#C93A3A',
        name: 'White (Red Ringer)',
        colorFamily: 'White',
        displayHueOrder: 1100,
    },
    1975: {
        hex: '#FAFAFA',
        ringerHex: '#C93A3A',
        name: 'White (Red Ringer)',
        colorFamily: 'White',
        displayHueOrder: 1100,
    },
    1976: {
        hex: '#FAFAFA',
        ringerHex: '#C93A3A',
        name: 'White (Red Ringer)',
        colorFamily: 'White',
        displayHueOrder: 1100,
    },
    1977: {
        hex: '#FAFAFA',
        ringerHex: '#2E9A63',
        name: 'White (Green Ringer)',
        colorFamily: 'White',
        displayHueOrder: 1100,
    },
    1978: {
        hex: '#FAFAFA',
        name: 'White',
        colorFamily: 'White',
        displayHueOrder: 1100,
    },
    1979: {
        hex: '#FAFAFA',
        name: 'White',
        colorFamily: 'White',
        displayHueOrder: 1100,
    },
    1980: {
        hex: '#FAFAFA',
        ringerHex: '#1D3F6E',
        name: 'White (Navy Ringer)',
        colorFamily: 'White',
        displayHueOrder: 1100,
    },
    1981: {
        hex: '#FAFAFA',
        name: 'White',
        colorFamily: 'White',
        displayHueOrder: 1100,
    },
    1982: {
        hex: '#FAFAFA',
        name: 'White',
        colorFamily: 'White',
        displayHueOrder: 1100,
    },
    1983: {
        hex: '#F2C94C',
        name: 'Yellow',
        colorFamily: 'Yellow',
        displayHueOrder: 300,
    },
    1984: {
        hex: '#AEB4B9',
        name: 'Heather Gray',
        colorFamily: 'Gray',
        displayHueOrder: 1200,
    },
    1985: {
        hex: '#FAFAFA',
        name: 'White',
        colorFamily: 'White',
        displayHueOrder: 1100,
    },
    1986: {
        hex: '#A9D3F5',
        name: 'Powder Blue',
        colorFamily: 'Blue',
        displayHueOrder: 650,
    },
    1987: {
        hex: '#F6C1A6',
        name: 'Pale Peach',
        colorFamily: 'Peach',
        displayHueOrder: 225,
    },
    1988: {
        hex: '#2D9C9C',
        name: 'Medium Teal',
        colorFamily: 'Teal',
        displayHueOrder: 500,
    },
    1989: {
        hex: '#FAFAFA',
        name: 'White',
        colorFamily: 'White',
        displayHueOrder: 1100,
    },
    1990: {
        hex: '#D4E3EF',
        name: 'Ice Blue',
        colorFamily: 'Blue',
        displayHueOrder: 660,
    },
    1991: {
        hex: '#AEB4B9',
        name: 'Heather Gray',
        colorFamily: 'Gray',
        displayHueOrder: 1200,
    },
    1992: {
        hex: '#F07E72',
        name: 'Salmon Coral',
        colorFamily: 'Peach',
        displayHueOrder: 175,
    },
    1993: {
        hex: '#A5B8E3',
        name: 'Periwinkle',
        colorFamily: 'Blue',
        displayHueOrder: 900,
    },
    1994: {
        hex: '#FAFAFA',
        name: 'White',
        colorFamily: 'White',
        displayHueOrder: 1100,
    },
    1995: {
        hex: '#FAFAFA',
        name: 'White',
        colorFamily: 'White',
        displayHueOrder: 1100,
    },
    1996: {
        hex: '#FAFAFA',
        name: 'White',
        colorFamily: 'White',
        displayHueOrder: 1100,
    },
    1997: {
        hex: '#AEB4B9',
        name: 'Heather Gray',
        colorFamily: 'Gray',
        displayHueOrder: 1200,
    },
    1998: {
        hex: '#F2A65A',
        name: 'Apricot',
        colorFamily: 'Peach',
        displayHueOrder: 250,
    },
    1999: {
        hex: '#FAFAFA',
        name: 'White',
        colorFamily: 'White',
        displayHueOrder: 1100,
    },
    2000: {
        hex: '#AEB4B9',
        name: 'Heather Gray',
        colorFamily: 'Gray',
        displayHueOrder: 1200,
    },
    2001: {
        hex: '#A9D3F5',
        name: 'Powder Blue',
        colorFamily: 'Blue',
        displayHueOrder: 650,
    },
    2002: {
        hex: '#DADDE2',
        name: 'Silver Gray',
        colorFamily: 'Gray',
        displayHueOrder: 1200,
    },
    2003: {
        hex: '#F7F0C6',
        name: 'Pale Cream Yellow',
        colorFamily: 'Yellow',
        displayHueOrder: 275,
    },
    2004: {
        hex: '#FAFAFA',
        name: 'White',
        colorFamily: 'White',
        displayHueOrder: 1100,
    },
    2005: {
        hex: '#AEB4B9',
        name: 'Heather Gray',
        colorFamily: 'Gray',
        displayHueOrder: 1200,
    },
    2006: {
        hex: '#B8CF62',
        name: 'Spring Green',
        colorFamily: 'Green',
        displayHueOrder: 400,
    },
    2007: {
        hex: '#FAFAFA',
        name: 'White',
        colorFamily: 'White',
        displayHueOrder: 1100,
    },
    2008: {
        hex: '#7893B0',
        name: 'Dusty Blue',
        colorFamily: 'Blue',
        displayHueOrder: 800,
    },
    2009: {
        hex: '#FAFAFA',
        name: 'White',
        colorFamily: 'White',
        displayHueOrder: 1100,
    },
    2010: {
        hex: '#B6B8C3',
        name: 'Cool Silver Gray',
        colorFamily: 'Gray',
        displayHueOrder: 1200,
    },
    2011: {
        hex: '#D3D3CF',
        name: 'Athletic Heather',
        colorFamily: 'Gray',
        displayHueOrder: 1200,
    },
    2012: {
        hex: '#F6F2E8',
        name: 'Warm Ivory',
        colorFamily: 'White',
        displayHueOrder: 1000,
    },
    2013: {
        hex: '#2B2B2B',
        name: 'Black',
        colorFamily: 'Black',
        displayHueOrder: 1300,
    },
    2014: {
        hex: '#FAFAFA',
        name: 'White',
        colorFamily: 'White',
        displayHueOrder: 1100,
    },
    2015: {
        hex: '#D64545',
        name: 'Red',
        colorFamily: 'Red',
        displayHueOrder: 100,
    },
    2016: {
        hex: '#3B6FC8',
        name: 'Performance Blue',
        colorFamily: 'Blue',
        displayHueOrder: 850,
    },
    2017: {
        hex: '#8AB6E8',
        name: 'Sky Blue',
        colorFamily: 'Blue',
        displayHueOrder: 775,
    },
    2018: {
        hex: '#AEB4B9',
        name: 'Heather Gray',
        colorFamily: 'Gray',
        displayHueOrder: 1200,
    },
    2019: {
        hex: '#FAFAFA',
        name: 'White',
        colorFamily: 'White',
        displayHueOrder: 1100,
    },
    2020: {
        hex: '#D64545',
        name: 'Red',
        colorFamily: 'Red',
        displayHueOrder: 100,
    },
    2021: {
        hex: '#3B79E3',
        name: 'Royal Blue',
        colorFamily: 'Blue',
        displayHueOrder: 825,
    },
    2022: {
        hex: '#9FDDEB',
        name: 'Ice Blue',
        colorFamily: 'Blue',
        displayHueOrder: 600,
    },
    2023: {
        hex: '#F79A87',
        name: 'Peach Coral',
        colorFamily: 'Peach',
        displayHueOrder: 200,
    },
    2024: {
        hex: '#6FB3F2',
        name: 'Cornflower Blue',
        colorFamily: 'Blue',
        displayHueOrder: 725,
    },
    2025: {
        hex: '#D64545',
        name: 'Red',
        colorFamily: 'Red',
        displayHueOrder: 100,
    },
    2026: {
        hex: '#F2E61C',
        name: 'Sunflower Yellow',
        colorFamily: 'Yellow',
        displayHueOrder: 350,
    },
}